# An example config file for an experiment.
# Keep this, it's used as an example to run the code after a user installs the project.

defaults:
  # Common setup.
  - setup
  # This file.
  - _self_
  # Reward model (from the configs/reward_model/ directory).
  - model: olmo2-32b-sft


######################################################################

max_seq_length: 4096
dataset_id: null
dataset_type: null
dataset_path: ${artifacts_dir}/shared/datasets/alignment-pipeline/${dataset_type}/merged/${dataset_id}
save_path: ${artifacts_dir}/shared/datasets/alignment-pipeline/${dataset_type}/filtered/${dataset_id}
seed: 43
