# @package _global_

# This config defines a common setup for experiments.
# Add it to the defaults of any experiment config.

# A random seed is generated for each run if you don't specify one.
# This is good to avoid overfitting your dev runs to specific seeds.
seed: ${generate_random_seed:}
# Cuda deterministic settings.
cuda_deterministic: false
cuda_strong_deterministic: false

# The root data and output directories to be used in experiments.
artifacts_dir: ${hydra:runtime.cwd}/artifacts
artifacts_subdir: private  # Can be private, shared, ...

# Outputs are saved in artifacts/${artifacts_subdir}/...
# so you can store them in different physical locations if you want
# by symlink-ing artifacts_subdir to a different location (private, shared, etc.)

# Outputs of an experiment are stored in a directory created by Hydra of the form
# ${artifacts_dir}/${artifacts_subdir}/outputs/${hydra.job.name}/${job_subdir}/runs/${now:%Y-%m-%d_%H-%M-%S-%f}
# This has been designed to allow flexibility and can be configured in the sections below.

# In that path, outputs of experiments generated by a script called job_name
# will be saved in outputs/${outputs_subdir}/job_name/${job_subdir}/...
# This can further be useful to tag experiments run from the same script.
job_subdir: dev

hydra:
  run:
    # Finally, this is where the outputs of an individual run will be stored.
    dir: ${artifacts_dir}/${artifacts_subdir}/outputs/${hydra.job.name}/${job_subdir}/runs/${now:%Y-%m-%d--%H-%M-%S-%f}
  job:
    chdir: true
  verbose: false  # Set to true for logging at debug level.

wandb:
  project: posttraining
  mode: online
  anonymous: allow
  tags:
    - development
  run_id: null
  run_name: null
  # Make outputs/wandb a symlink if you want to save the wandb summaries elsewhere.
  # Same as with outputs_subdir.
  global_dir: ${hydra:runtime.cwd}/outputs
  use_global_dir: false # Otherwise, use the cwd of the experiment.

run_dir: ${hydra:run.dir}
resuming_dir: null
resuming_hash: null

resuming:
  resume: false
  use_commit: false
  wandb_cache_bust: 0 # Limitation of wandb. Cannot create runs with the same ID if deleted previously.
                      # Use this to refresh the id of the run and make it a "new" run.
  ignore_keys:
    # Keys in the config to ignore when checking that the run is resuming with the same config.
    # Can be a deep key e.g. model.optimizer.lr
    # To resume if stared in a different location.
    - run_dir
    - resuming_dir
    - resuming_hash
    - artifacts_dir
    - artifacts_subdir
    - job_subdir
    - wandb
    # To be able to add keys on the fly and force resume.
    - resuming.ignore_keys
