defaults:
  - setup
  - _self_
  # Model (from the configs/model/ directory).
  - model: apertus-8b
  # Dataset (from the configs/dataset/ directory).
  - dataset: tulu-3-sft-mixture-split
  # Optional preset for training parameters.
  - optional preset: none

######################################################################

wandb:
  project: posttraining-sft

dataset_args:
  debug_oom: false # Reorder the dataset with largest batch first to test OOM
  debug_subsample:
    train: 0
    eval: 0
  shuffle: true

script_args:
  dataset_name: ${dataset_args.dataset_name}
  dataset_train_split: ${dataset_args.train_split.name}
  dataset_test_split: ${dataset_args.eval_split.name}

accelerate_config: "src/post_training/configs/accelerate/ds-zero1.yaml"
trainer: plw # can only take values: sft, plw, ln-plw, irl
plw_args:
  prompt_loss_weight: 0.0
  sequence_level_loss: false

# These arguments are only specified to make sure the config hash is different when these values change.
# They are not used in the training script.
global_batch_size: 32
num_nodes: 1

training_args:
  bf16: true
  max_seq_length: 4096
  max_grad_norm: 1
  learning_rate: 5.0e-06
  lr_scheduler_type: linear
  warmup_ratio: 0.03
  warmup_steps: 0
  optim: adamw_torch
  optim_args: null
  weight_decay: 0.0
  num_train_epochs: 1
  packing: false
  dataloader_drop_last: true
  remove_unused_columns: false # required for custom data collator
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false # https://pytorch.org/docs/stable/checkpoint.html, https://github.com/huggingface/trl/issues/1348
  average_tokens_across_devices: true # More accurate loss.
  logging_first_step: true
  logging_steps: 1
  per_device_eval_batch_size: 2
  eval_strategy: no
  eval_steps: null
  eval_on_start: false
  save_strategy: steps
  save_steps: 1000
  save_total_limit: 3
  report_to: wandb
  seed: ${seed}
  dataset_num_proc: 32
  dataloader_num_workers: ${training_args.per_device_train_batch_size}

seed: 42

resuming:
  resume: false
  ignore_keys:
    - run_dir
    - resuming_dir
    - resuming_hash
    - artifacts_dir
    - artifacts_subdir
    - job_subdir
    - wandb
    - resuming.ignore_keys
    - training_args.logging_dir
    - training_args.dataloader_num_workers
    - training_args.dataset_num_proc
    - training_args.save_steps
